# The Main Themes Of Microbiology

[Microbiology](https://en.wikipedia.org/wiki/Microbiology) (from Greek μῑκρος, mīkros, "small"; βίος, bios, "life"; and -λογία, -logia) is the scientific study of microorganisms, those being unicellular (single cell), multicellular (cell colony), or acellular (lacking cells). A unicellular organism, also known as a single-celled organism, is an organism that consists of a single cell, unlike a multicellular organism that consists of multiple cells. Unicellular organisms fall into two general categories: prokaryotic organisms and eukaryotic organisms. All prokaryotes are unicellular and are classified into bacteria and archaea. Many eukaryotes are multicellular, but many are unicellular such as protozoa, unicellular algae, and unicellular fungi. Unicellular organisms are thought to be the oldest form of life, with early protocells possibly emerging 3.8–4.0 billion years ago. Multicellular organisms are organisms that consist of more than one cell, in contrast to unicellular organisms.  All species of animals, land plants and most fungi are multicellular, as are many algae, whereas a few organisms are partially uni- and partially multicellular, like slime molds and social amoebae such as the genus Dictyostelium.  

Microbiology encompasses numerous sub-disciplines including virology, bacteriology, protistology, mycology, immunology and parasitology.

Eukaryotic microorganisms possess membrane-bound organelles and include fungi and protists, whereas prokaryotic organisms—all of which are microorganisms—are conventionally classified as lacking membrane-bound organelles and include Bacteria and Archaea. Microbiologists traditionally relied on culture, staining, and microscopy. However, less than 1% of the microorganisms present in common environments can be cultured in isolation using current means.  Microbiologists often rely on molecular biology tools such as DNA sequence based identification, for example the 16S rRNA gene sequence used for bacteria identification.

[Viruses](https://en.wikipedia.org/wiki/Virus) have been variably classified as organisms,  as they have been considered either as very simple microorganisms or very complex molecules. [Prions](https://en.wikipedia.org/wiki/Prion), never considered as microorganisms, have been investigated by virologists, however, as the clinical effects traced to them were originally presumed due to chronic viral infections, and virologists took search—discovering "infectious proteins".

The existence of microorganisms was predicted many centuries before they were first observed, for example by the Jains in India and by Marcus Terentius Varro in ancient Rome. The first recorded microscope observation was of the fruiting bodies of moulds, by Robert Hooke in 1666, but the Jesuit priest Athanasius Kircher was likely the first to see microbes, which he mentioned observing in milk and putrid material in 1658. Antonie van Leeuwenhoek is considered a father of microbiology as he observed and experimented with microscopic organisms in the 1670s, using simple microscopes of his own design. Scientific microbiology developed in the 19th century through the work of [Louis Pasteur](https://en.wikipedia.org/wiki/Louis_Pasteur) and in medical microbiology [Robert Koch](https://en.wikipedia.org/wiki/Robert_Koch).

(ref:leeuv) As the first acknowledged microscopist and microbiologist in history, [Antonie van Leeuwenhoek](https://commons.wikimedia.org/wiki/File:Anthonie_van_Leeuwenhoek_(1632-1723)._Natuurkundige_te_Delft_Rijksmuseum_SK-A-957.jpeg) was the first to undisputedly discover (observe), study, describe, conduct scientific experiments with a large array of microscopic organisms (including bacteria, which he called “animalcules”) and relatively determine their size, using single-lensed microscopes of his own design.


(ref:leeumic) [Van Leeuwenhoek's microscopes by Henry Baker.](https://en.wikipedia.org/wiki/Microbiology#/media/File:Van_Leeuwenhoek's_microscopes_by_Henry_Baker.jpg)

(ref:beij) [Martinus Beijerinck](https://commons.wikimedia.org/wiki/File:Martinus_Willem_Beijerinck_in_his_laboratory.jpg), the founding father of the Delft School of Microbiology, in his laboratory. Beijerinck is often considere as a founder of virology, environmental microbiology, and industrial microbiology.

In 1676, [Antonie van Leeuwenhoek](https://en.wikipedia.org/wiki/Antonie_van_Leeuwenhoek), who lived most of his life in Delft, Netherlands, observed bacteria and other microorganisms using a single-lens microscope of his own design.

(ref:repl) [A replica of a microscope by van Leeuwenhoek](https://commons.wikimedia.org/wiki/File:Leeuwenhoek_Microscope.png)

(ref:let) [A 1677 letter from van Leeuwenhoek to Oldenburg, with the latter's English translation behind, the full correspondence remains in the Royal Society Library](https://commons.wikimedia.org/wiki/File:Antoni_van_Leeuwenhoek_letters_to_the_Royal_Society_3.jpg
)

He is considered a father of microbiology as he pioneered the use of simple single-lensed microscopes of his own design.  While Van Leeuwenhoek is often cited as the first to observe microbes, Robert Hooke made his first recorded microscopic observation, of the fruiting bodies of moulds, in 1665.  It has, however, been suggested that a Jesuit priest called Athanasius Kircher was the first to observe microorganisms. Kircher was among the first to design magic lanterns for projection purposes, so he must have been well acquainted with the properties of lenses.  He wrote "Concerning the wonderful structure of things in nature, investigated by Microscope" in 1646, stating "who would believe that vinegar and milk abound with an innumerable multitude of worms." He also noted that putrid material is full of innumerable creeping animalcules. He published his Scrutinium Pestis (Examination of the Plague) in 1658, stating correctly that the disease was caused by microbes, though what he saw was most likely red or white blood cells rather than the plague agent itself. Innovative laboratory glassware and experimental methods developed by [Louis Pasteur](https://commons.wikimedia.org/wiki/File:Albert_Edelfelt_-_Louis_Pasteur_-_1885.jpg) and other biologists contributed to the young field of bacteriology in the late 19th century.

The field of bacteriology (later a subdiscipline of microbiology) was founded in the 19th century by Ferdinand Cohn, a botanist whose studies on algae and photosynthetic bacteria led him to describe several bacteria including Bacillus and Beggiatoa. Cohn was also the first to formulate a scheme for the taxonomic classification of bacteria, and to discover endospores.  Louis Pasteur and Robert Koch were contemporaries of Cohn, and are often considered to be the fathers of modern microbiology  and medical microbiology, respectively.  Pasteur is most famous for his series of experiments designed to disprove the then widely held theory of [spontaneous generation](https://en.wikipedia.org/wiki/Spontaneous_generation), thereby solidifying microbiology's identity as a biological science.  One of his students, Adrien Certes, is considered the founder of marine microbiology.  Pasteur also designed methods for food preservation (pasteurization) and vaccines against several diseases such as anthrax, fowl cholera and rabies.  Koch is best known for his contributions to the germ theory of disease, proving that specific diseases were caused by specific pathogenic microorganisms. He developed a series of criteria that have become known as the Koch's postulates. Koch was one of the first scientists to focus on the isolation of bacteria in pure culture resulting in his description of several novel bacteria including Mycobacterium tuberculosis, the causative agent of tuberculosis. While Pasteur and Koch are often considered the founders of microbiology, their work did not accurately reflect the true diversity of the microbial world because of their exclusive focus on microorganisms having direct medical relevance. It was not until the late 19th century and the work of [Martinus Beijerinck](https://en.wikipedia.org/wiki/Martinus_Beijerinck) and [Sergei Winogradsky](https://en.wikipedia.org/wiki/Sergei_Winogradsky) that the true breadth of microbiology was revealed.  Beijerinck made two major contributions to microbiology: the discovery of viruses and the development of enrichment culture techniques.  While his work on the [tobacco mosaic virus](https://en.wikipedia.org/wiki/Tobacco_mosaic_virus) established the basic principles of virology, it was his development of enrichment culturing that had the most immediate impact on microbiology by allowing for the cultivation of a wide range of microbes with wildly different physiologies. Winogradsky was the first to develop the concept of chemolithotrophy and to thereby reveal the essential role played by microorganisms in geochemical processes.  He was responsible for the first isolation and description of both nitrifying and nitrogen-fixing bacteria.  French-Canadian microbiologist [Felix d'Herelle](https://en.wikipedia.org/wiki/Félix_d%27Hérelle) co-discovered bacteriophages in 1917 and was one of the earliest applied microbiologists. [Joseph Lister](https://en.wikipedia.org/wiki/Joseph_Lister) was the first to use phenol disinfectant on the open wounds of patients. The branches of microbiology can be classified into applied sciences, or divided according to taxonomy, as is the case with bacteriology, mycology, protozoology, virology, phycology, and microbial ecology. There is considerable overlap between the specific branches of microbiology with each other and with other disciplines, and certain aspects of these branches can extend beyond the traditional scope of microbiology. A pure research branch of microbiology is termed cellular microbiology.

While some fear microbes due to the association of some microbes with various human diseases, many microbes are also responsible for numerous beneficial processes such as industrial fermentation (e.g. the production of alcohol, vinegar and dairy products), antibiotic production and act as molecular vehicles to transfer DNA to complex organisms such as plants and animals. Scientists have also exploited their knowledge of microbes to produce biotechnologically important enzymes such as Taq polymerase,  reporter genes for use in other genetic systems and novel molecular biology techniques such as the yeast two-hybrid system.

Bacteria can be used for the industrial production of amino acids. Corynebacterium glutamicum is one of the most important bacterial species with an annual production of more than two million tons of amino acids, mainly L-glutamate and L-lysine.  Since some bacteria have the ability to synthesize antibiotics, they are used for medicinal purposes, such as Streptomyces to make aminoglycoside antibiotics.

(ref:ferm) [Fermenting tanks with yeast being used to brew beer.](https://commons.wikimedia.org/wiki/File:Cuves_de_fermentations.jpg)

A variety of biopolymers, such as polysaccharides, polyesters, and polyamides, are produced by microorganisms. Microorganisms are used for the biotechnological production of biopolymers with tailored properties suitable for high-value medical application such as tissue engineering and drug delivery. Microorganisms are for example used for the biosynthesis of xanthan, alginate, cellulose, cyanophycin, poly(gamma-glutamic acid), levan, hyaluronic acid, organic acids, oligosaccharides polysaccharide and polyhydroxyalkanoates. Microorganisms are beneficial for microbial biodegradation or bioremediation of domestic, agricultural and industrial wastes and subsurface pollution in soils, sediments and marine environments. The ability of each microorganism to degrade toxic waste depends on the nature of each contaminant. Since sites typically have multiple pollutant types, the most effective approach to microbial biodegradation is to use a mixture of bacterial and fungal species and strains, each specific to the biodegradation of one or more types of contaminants. Symbiotic microbial communities confer benefits to their human and animal hosts health including aiding digestion, producing beneficial vitamins and amino acids, and suppressing pathogenic microbes. Some benefit may be conferred by eating fermented foods, probiotics (bacteria potentially beneficial to the digestive system) or prebiotics (substances consumed to promote the growth of probiotic microorganisms). The ways the microbiome influences human and animal health, as well as methods to influence the microbiome are active areas of research. Research has suggested that microorganisms could be useful in the treatment of cancer. Various strains of non-pathogenic clostridia can infiltrate and replicate within solid tumors. Clostridial vectors can be safely administered and their potential to deliver therapeutic proteins has been demonstrated in a variety of preclinical models. Some bacteria are used to study fundamental mechanism. An example of model bacteria used to study motility  or the production of polysaccharides and development is Myxococcus xanthus.
