# Microbial Genetics

Since the discovery of microorganisms by Robert Hooke and Antoni van Leeuwenhoek during the period 1665-1885[2] they have been used to study many processes and have had applications in various areas of study in genetics. For example: Microorganisms' rapid growth rates and short generation times are used by scientists to study evolution. Robert Hooke and Antoni van Leeuwenhoek discoveries involved depictions, observations, and descriptions of microorganisms.[3] Mucor is the microfungus that Hooke presented and gave a depiction of.[4] His contribution being, Mucor as the first microorganism to be illustrated. Antoni van Leeuwenhoek’s contribution to the microscopic protozoa and microscopic bacteria yielded to scientific observations and descriptions.[4] These contributions were accomplished by a simple microscope, which led to the understanding of microbes today and continues to progress scientists understanding.  [5] Microbial genetics also has applications in being able to study processes and pathways that are similar to those found in humans such as drug metabolism.[6]

Bacterial genetics is the subfield of genetics devoted to the study of bacteria. Bacterial genetics are subtly different from eukaryotic genetics, however bacteria still serve as a good model for animal genetic studies. One of the major distinctions between bacterial and eukaryotic genetics stems from the bacteria's lack of membrane-bound organelles (this is true of all prokaryotes. While it is a fact that there are prokaryotic organelles, they are never bound by a lipid membrane, but by a shell of proteins), necessitating protein synthesis occur in the cytoplasm.

Genetically modified bacteria were the first organisms to be modified in the laboratory, due to their simple genetics.[1] These organisms are now used for several purposes, and are particularly important in producing large amounts of pure human proteins for use in medicine.[2]

Most bacteria have a single circular chromosome that can range in size from only 160,000 base pairs in the endosymbiotic bacteria Carsonella ruddii,[112] to 12,200,000 base pairs (12.2 Mbp) in the soil-dwelling bacteria Sorangium cellulosum.[113] There are many exceptions to this, for example some Streptomyces and Borrelia species contain a single linear chromosome,[114][115] while some Vibrio species contain more than one chromosome.[116] Bacteria can also contain plasmids, small extra-chromosomal molecules of DNA that may contain genes for various useful functions such as antibiotic resistance, metabolic capabilities, or various virulence factors.[117]

Bacteria genomes usually encode a few hundred to a few thousand genes. The genes in bacterial genomes are usually a single continuous stretch of DNA and although several different types of introns do exist in bacteria, these are much rarer than in eukaryotes.[118]

Bacteria, as asexual organisms, inherit an identical copy of the parent's genomes and are clonal. However, all bacteria can evolve by selection on changes to their genetic material DNA caused by genetic recombination or mutations. Mutations come from errors made during the replication of DNA or from exposure to mutagens. Mutation rates vary widely among different species of bacteria and even among different clones of a single species of bacteria.[119] Genetic changes in bacterial genomes come from either random mutation during replication or "stress-directed mutation", where genes involved in a particular growth-limiting process have an increased mutation rate.[120]

Some bacteria also transfer genetic material between cells. This can occur in three main ways. First, bacteria can take up exogenous DNA from their environment, in a process called transformation.[121] Many bacteria can naturally take up DNA from the environment, while others must be chemically altered in order to induce them to take up DNA.[122] The development of competence in nature is usually associated with stressful environmental conditions, and seems to be an adaptation for facilitating repair of DNA damage in recipient cells.[123] The second way bacteria transfer genetic material is by transduction, when the integration of a bacteriophage introduces foreign DNA into the chromosome. Many types of bacteriophage exist, some simply infect and lyse their host bacteria, while others insert into the bacterial chromosome.[124] Bacteria resist phage infection through restriction modification systems that degrade foreign DNA,[125] and a system that uses CRISPR sequences to retain fragments of the genomes of phage that the bacteria have come into contact with in the past, which allows them to block virus replication through a form of RNA interference.[126][127] The third method of gene transfer is conjugation, whereby DNA is transferred through direct cell contact. In ordinary circumstances, transduction, conjugation, and transformation involve transfer of DNA between individual bacteria of the same species, but occasionally transfer may occur between individuals of different bacterial species and this may have significant consequences, such as the transfer of antibiotic resistance.[128][129] In such cases, gene acquisition from other bacteria or the environment is called horizontal gene transfer and may be common under natural conditions.[130]



Like other organisms, bacteria also breed true and maintain their characteristics from generation to generation, yet at the same time, exhibit variations in particular properties in a small proportion of their progeny. Though heritability and variations in bacteria had been noticed from the early days of bacteriology, it was not realised then that bacteria too obey the laws of genetics. Even the existence of a bacterial nucleus was a subject of controversy. The differences in morphology and other properties were attributed by Nageli in 1877, to bacterial pleomorphism, which postulated the existence of a single, a few species of bacteria, which possessed a protein capacity for a variation. With the development and application of precise methods of pure culture, it became apparent that different types of bacteria retained constant form and function through successive generations. This led to the concept of monomorphism.

Transformation[edit]
Transformation in bacteria was first observed in 1928 by Frederick Griffith and later (in 1944) examined at the molecular level by Oswald Avery and his colleagues who used the process to demonstrate that DNA was the genetic material of bacteria.[1] In transformation, a cell takes up extraneous DNA found in the environment and incorporates it into its genome (genetic material) through recombination.[2] Not all bacteria are competent to be transformed, and not all extracellular DNA is competent to transform. To be competent to transform, the extracellular DNA must be double-stranded and relatively large. To be competent to be transformed, a cell must have the surface protein Competent Factor', which binds to the extracellular DNA in an energy requiring reaction. However bacteria that are not naturally competent can be treated in such a way to make them competent, usually by treatment with calcium chloride, which make them more permeable.[3]

Bacterial conjugation[edit]
Bacterial conjugation is the transfer of genetic material (plasmid) between bacterial cells by direct cell-to-cell contact or by a bridge-like connection between two cells.[1] Discovered in 1946 by Joshua Lederberg and Edward Tatum,[2] conjugation is a mechanism of horizontal gene transfer as are transformation and transduction although these two other mechanisms do not involve cell-to-cell contact.[3]

Bacterial conjugation is often regarded as the bacterial equivalent of sexual reproduction or mating since it involves the exchange of genetic material. During conjugation the donor cell provides a conjugative or mobilizable genetic element that is most often a plasmid or transposon.[4][5] Most conjugative plasmids have systems ensuring that the recipient cell does not already contain a similar element.

The genetic information transferred is often beneficial to the recipient. Benefits may include antibiotic resistance, xenobiotic tolerance or the ability to use new metabolites.[6] Such beneficial plasmids may be considered bacterial endosymbionts. Other elements, however, may be viewed as bacterial parasites and conjugation as a mechanism evolved by them to allow for their spread.
